# Generated by Django 4.1.2 on 2022-10-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('numero_ci', models.IntegerField(max_length=8)),
                ('numero_cel', models.IntegerField(max_length=9)),
            ],
        ),
    ]
