# Generated by Django 4.1.2 on 2022-10-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_consultasmedicas_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('dias_consulta', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ConsultasMedicas',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='numero_func',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_cel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_ci',
            field=models.IntegerField(),
        ),
    ]
