# Generated by Django 4.0.4 on 2022-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_configuracion_delete_consultamedica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('fecha_de_nacimiento', models.DateField()),
                ('numero_ci', models.IntegerField()),
                ('numero_cel', models.IntegerField()),
                ('motivo_consulta', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
